import { IAIProvider, AICompletionResult } from "./aiProvider.interface.js";

export class ClaudeProvider implements IAIProvider {
  name = "Anthropic Claude";
  private apiKey: string;
  private model: string;

  constructor(apiKey: string, model = "claude-3-5-sonnet-20241022") {
    this.apiKey = apiKey;
    this.model = model;
  }

  async generateCompletion(query: string, systemContext: string): Promise<AICompletionResult> {
    const url = "https://api.anthropic.com/v1/messages";

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": this.apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: this.model,
          system: `You are the MaintenX OS Operational Intelligence Assistant for manufacturing plants.
Use the following real-time factory context to answer the operator or manager accurately and concisely.
Ground-Truth Context:
${systemContext}`,
          messages: [
            {
              role: "user",
              content: query,
            },
          ],
          max_tokens: 500,
          temperature: 0.2,
        }),
        signal: AbortSignal.timeout(15000),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Claude HTTP ${response.status}: ${errorText}`);
      }

      const data = (await response.json()) as any;
      const reply = data.content?.[0]?.text?.trim() || "No response generated by Anthropic Claude.";

      return {
        reply,
        tag: "Claude Deep Operational Inference",
        confidence: 0.96,
        sources: ["Anthropic Claude Engine", "MaintenX Data Fabric"],
        provider: "Anthropic Claude",
        modelUsed: this.model,
      };
    } catch (err: any) {
      console.error("[Claude Provider Error]:", err.message);
      throw new Error(`AI Provider Failure (Anthropic Claude): ${err.message}`);
    }
  }
}
