import { IAIProvider, AICompletionResult } from "./aiProvider.interface.js";

export class GeminiProvider implements IAIProvider {
  name = "Google Gemini";
  private apiKey: string;
  private model: string;

  constructor(apiKey: string, model = "gemini-1.5-flash") {
    this.apiKey = apiKey;
    this.model = model;
  }

  async generateCompletion(query: string, systemContext: string): Promise<AICompletionResult> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: {
            parts: [
              {
                text: `You are the MaintenX OS Operational Intelligence Assistant for manufacturing plants.
Use the following real-time factory context to answer the operator or manager accurately and concisely.
Ground-Truth Context:
${systemContext}`,
              },
            ],
          },
          contents: [
            {
              role: "user",
              parts: [{ text: query }],
            },
          ],
          generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 500,
          },
        }),
        signal: AbortSignal.timeout(15000),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini HTTP ${response.status}: ${errorText}`);
      }

      const data = (await response.json()) as any;
      const reply =
        data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "No response generated by Google Gemini.";

      return {
        reply,
        tag: "Gemini Analytical Intelligence",
        confidence: 0.94,
        sources: ["Google Gemini Engine", "Plant SCADA Data"],
        provider: "Google Gemini",
        modelUsed: this.model,
      };
    } catch (err: any) {
      console.error("[Gemini Provider Error]:", err.message);
      throw new Error(`AI Provider Failure (Google Gemini): ${err.message}`);
    }
  }
}
